version: '3.8'

services:
  angular-app:
    image: nginx:alpine
    container_name: angular-app
    ports:
      - "80:80"
    volumes:
      - ./dist/angular-kickstart:/usr/share/nginx/html
    # Uncomment and add custom nginx config if needed
    # - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always

